name: Markdown CI

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "**/*.md"
          config_file: .markdownlint.yaml
          dot: true